apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sso
  name: keycloak-db-secret
stringData:
  POSTGRES_DATABASE: keycloak
  POSTGRES_EXTERNAL_ADDRESS: %EXT_DB_IP_ADDRESS%
  POSTGRES_EXTERNAL_PORT: "5432"
  POSTGRES_HOST: keycloak-postgresql
  POSTGRES_PASSWORD: keycloakpasswd
  POSTGRES_USERNAME: keycloakuser
